[build]
  base = "apps/web"
  publish = ".next"
  command = "npm run build"

[functions]
  included_files = [".next/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_RUNTIME = "edge"
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/api/revalidate"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-store"
